version: "3.7"
services:
  fake-production:
    build: ./fp-app
    ports:
      - "8080:8080"
    links:
      - fp-postgres
    container_name: fp-app
  fp-postgres:
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    container_name: fp-postgres
    environment:
      POSTGRES_PASSWORD: fp-postgres-pass
    volumes:
      # - ./fp-postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - fp-pg-data:/var/lib/postgresql/data

volumes:
  fp-pg-data:
